---
  # brew tap
  - name: brew tap
    homebrew_tap: tap="{{ item }}" state=present
    with_items: '{{ homebrew_taps }}'

  # update homebrew
  - name: brew update
    homebrew: update_homebrew=yes

  # brew
  - name: install brew package
    homebrew: >
      name={{ item.name }}
      state={{ item.state | default('latest') }}
      install_options={{
        item.install_options | default() | join(',')
        if item.install_options is not string
        else item.install_options
      }}
    with_items: '{{ homebrew_packages }}'
    register: brew_result

  # cask
  - name: install homebrew-cask
    homebrew: name=cask state=latest

  - name: install cask package
    homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
    with_items: '{{ homebrew_cask_packages }}'
    register: cask_result

  # zsh
  - name: install oh-my-zsh
    shell: "sh -c $(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    args:
      creates: ~/.oh-my-zsh
