---
  homebrew_taps:
    - homebrew/binary
    - homebrew/dupes
    - caskroom/cask
    - caskroom/versions
    - sanemat/font
    - caskroom/fonts
    - homebrew/apache
    - homebrew/php

  homebrew_packages:
    - { name: ansible }
    - { name: curl }
    - { name: git }
    - { name: python }
    - { name: ricty }
    - { name: wget }
    - { name: zsh }
    - { name: zsh-completions }
    - { name: ruby }
    - { name: httpd24 }
    - { name: mysql }
    - { name: php56 }
    - { name: php56-intl }
    - { name: php56-opcache }
    - { name: php56-apcu }
    - { name: php56-mcrypt }
    - { name: php56-xdebug }
    - { name: php56-xhprof }
    - { name: phpunit }

  homebrew_cask_packages:
    - { name: atom }
    - { name: cakebrew }
    - { name: coteditor }
    - { name: dropbox }
    - { name: filezilla }
    - { name: firefox }
    - { name: font-migu-1m }
    - { name: font-m-plus }
    - { name: google-chrome }
    - { name: google-drive }
    - { name: google-japanese-ime }
    - { name: iterm2 }
    - { name: libreoffice }
    - { name: skype }
    - { name: slack }
    - { name: sublime-text3 }
    - { name: the-unarchiver }
    - { name: vagrant }
    - { name: virtualbox }
    - { name: vlc }
    - { name: xquartz }
